apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: set1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: web
          image: mahendrshinde/myweb:1
          ports:
            - containerPort: 80