apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: web
        image: mahendrshinde/heavy-app:latest
        resources:
          limits:
            memory: "20Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2-svc
spec:
  type: LoadBalancer
  selector:
    app: app2
  ports:
    - port: 8081
      targetPort: 80