apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 5
  revisionHistoryLimit: 5
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: web
        image: mahendrshinde/myweb:1
        ports:
        - containerPort: 80
